redis:
  sync-enabled: false
  host: 172.18.0.1
  port: 6379
  password: null
  clientName: Serveur_mc

database:
  host: 172.18.0.1
  port: 3306
  user: user
  dbname: dbname
  password: password

# sql or redis
messenger: sql

servername: "Survie"
survival-servers:
  - "survie"
ressources-servername: "ressources"

world:
  overworld: "world"
  nether: "world_nether"
  end: "world_the_end"

plan-rtp-balancer: true

# Send approval request to discord on each non whitelisted commad by non-trusted users.
command-approval: false

global-chat: true