name: Core
version: ${project.version}
main: fr.iban.bukkitcore.CoreBukkitPlugin
api-version: 1.16
authors: [ Iban ]
softdepend: [ Essentials, Plan ]
folia-supported: true

commands:
  options:
  core:
    permission: servercore.papercore.reload
  recompenses:
  abbc:
    permission: servercore.abbc
  bungeebroadcast:
    aliases:
      - bbc
    permission: servercore.bbc
